---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ not (lookup('env', 'MOLECULE_DEBUG') | bool or molecule_yml.provisioner.log|default(false) | bool) }}"
  tasks:
    - name: Enumerate all tagged instances in ec2
      ec2_instance_facts:
        region: 'ap-southeast-2'
        filters:
          "tag:Name": "Molecule Testing Instance"
      register: vmfacts


    - debug: msg="{{ item.instance_id }}"
      with_items: "{{ vmfacts.instances }}"


    - name: Delete ami instance in ec2
      ec2:
        region: 'ap-southeast-2'
        state: "{{ action }}"
        instance_ids: '{{ item.instance_id }}'
      with_items: '{{ vmfacts.instances }}'
      register: server


    - name: Wait for instance(s) deletion to complete
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: ec2_jobs
      until: ec2_jobs.finished
      retries: 300
      with_items: "{{ server.results }}"

    # Mandatory configuration for Molecule to function.

    - name: Populate instance config
      set_fact:
        instance_conf: {}

    - name: Dump instance config
      copy:
        content: "{{ instance_conf | to_json | from_json | molecule_to_yaml | molecule_header }}"
        dest: "{{ molecule_instance_config }}"