---
driver:
  name: ec2
  ssh_connection_options:
    - -o ControlPersist=30m

lint:
  name: yamllint
  options:
    config-file: .yamllint

platforms:
  - name: ec2-rhel
    image: ami-67589505
    instance_type: t2.medium
    ssh_user: ec2-user
    vpc_subnet_id: subnet-8c474eeb
    region: ap-southeast-2
    security_group_vpc: ${STIG_CI_AWS_VPC_ID}


provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
  config_options:
    defaults:
      remote_tmp: /tmp/.ansible
      retry_files_enabled: false

scenario:
  name: aws
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence  #  Current bug with lineinfile module
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: false
